FROM example_www:base

EXPOSE 3000

WORKDIR /app
CMD ["npm", "start"]

# install dependencies of two sub-modules
COPY ./module1/package.json /app/module1/package.json
RUN cd /module1 && npm install

COPY ./module2/package.json /app/module2/package.json
RUN cd /app/module2 && npm install

# install dependencies of main project
COPY ./package.json /app/package.json
COPY ./bower.json /app/bower.json
RUN cd /app && npm install && bower install

# pre-compile js, less and sass files
COPY ./public /app/public
COPY ./assert /app/assert
COPY ./Gruntfile.js /app/Gruntfile.js
RUN gulp build

# copy source code
COPY ./ /app/